lane :Internal do
      Dir.chdir ".." do
        sh("git", "pull")
       end
      build_number = number_of_commits()
      Dir.chdir ".." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "apk", "--build-number=#{build_number}")
      end

end